# Generated by Django 2.0.7 on 2018-09-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Comment',
        ),
    ]
